name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # Remove the cache line or change to cache: 'npm' without specifying lockfile
        cache: 'npm'

    - name: Install dependencies
      run: npm install  # Change from npm ci to npm install

    - name: Run tests (if any)
      run: npm test --if-present

    - name: Notify Render (Webhook Deployment)
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
