name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install body-parser@^1.20.2
        npm install cron@^2.3.0
        npm install express@^4.18.2
        npm install json2csv@^5.0.7
        npm install node-telegram-bot-api@^0.64.0

    - name: Verify installation
      run: |
        npm list --depth=0
        echo "Dependencies installed successfully!"

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        curl -s -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
        echo "Render deployment triggered!"
        
    - name: Send Telegram notification
      if: success() && github.ref == 'refs/heads/main'
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.ADMIN_CHAT_ID }}" \
          -d text="✅ Deployment started! New version of Xuppronix bot is being deployed."
